easy_admin:
    entities:
       User:
           class: App\Entity\User
           list:
             title: "Manage %%entity_label%%s"
             fields: ['id', 'username', 'email', 'location', 'lastLogin']
             actions:
               - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-outline-success' }
               - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-outline-danger' }
           form:
             fields: ['username', 'email', 'location', 'lastLogin']
             max_results: 10
